title: The Cogitator
email: adam.arold@appcraft.hu
description: >
  I'm Adam Arold and my aim with this site is to share insight about technologies I touch during my work. If you have any questions feel free to reach out using the Contact link above.
baseurl: ""
url: "http://the-cogitator.com"
twitter_username: addamsson
github_username:  adam-arold
incremental: true

markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Adam Arold"