title: The Cogitator
email: arold.adam@gmail.com
description: >
  I'm Adam Arold and my aim with this site is to share insight about technologies I touch during my work. If you have any questions feel free to reach out using the Contact link below.
baseurl: ""
url: "http://the-cogitator.com"
twitter_username: addamsson
github_username:  adam-arold
incremental: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: redcarpet
markdown: redcarpet

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Adam Arold"